---
ID: "42c61013-ebff-4ace-a2e0-f2b423f8aff3"
Parent: "ffe55434-ddbb-4b30-87ae-784afcf5a90b"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: /sitecore/content/Basic/Basic/Settings/Shared Sites Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230411T170639Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\79hNWxfoQm
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\79hNWxfoQm
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fea012ac-fadc-4212-a022-ae2132b51018"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\79hNWxfoQm
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230411T170639Z
